/**
 * Certificate Routes for ADALAT360
 * BSA §63 Electronic Evidence Certificate Generator
 * POST   /api/certificates/document/:id - Generate BSA §63 certificate for document
 * GET    /api/certificates/:id - Get certificate
 * GET    /api/certificates/document/:id - List certificates for document
 * POST   /api/certificates/:id/regenerate - Regenerate certificate
 */

import express from 'express';
import { z } from 'zod';
import { prisma } from '../index.js';
import { authenticate, requireRole, requireDocumentAccess, auditLog } from '../middleware/rbac.js';
import { sha256 } from '../utils/crypto.js';

const router = express.Router();

/**
 * POST /api/certificates/document/:id
 * Generate BSA §63 electronic evidence certificate
 * This is deterministic templating - NO LLM
 */
router.post(
  '/document/:id',
  authenticate,
  requireRole('IO', 'PP', 'FSL', 'CRT', 'SYS'),
  requireDocumentAccess,
  auditLog('generate_certificate', 'DOCUMENT'),
  async (req, res, next) => {
    try {
      const document = await prisma.document.findUnique({
        where: { id: req.params.id },
        include: {
          case: { select: { id: true, caseNumber: true, title: true, department: true } },
          uploader: { select: { name: true, role: true, serviceBarId: true } },
          custodyEntries: {
            orderBy: { timestamp: 'asc' },
            include: { actor: { select: { name: true, role: true } } },
            take: 20,
          },
        },
      });

      if (!document) {
        return res.status(404).json({ error: 'Document not found' });
      }

      // Check if certificate already exists
      const existing = await prisma.certificate.findFirst({
        where: { documentId: document.id },
        orderBy: { issuedAt: 'desc' },
      });

      if (existing) {
        return res.status(409).json({
          error: 'Certificate already exists for this document',
          certificateId: existing.id,
        });
      }

      // Generate certificate text using deterministic template
      const certText = generateBSA63Certificate(document);
      const hashSummary = sha256(certText);

      // Create certificate record
      const certificate = await prisma.certificate.create({
        data: {
          documentId: document.id,
          caseId: document.caseId,
          generatedBy: req.user.id,
          certText,
          hashSummary,
        },
      });

      // Create custody entry
      const prevHash = await getLastCustodyHash(document.caseId);
      const entryHash = sha256(`${prevHash || ''}|CERTIFICATE|${req.user.id}|${new Date().toISOString()}`);

      await prisma.custodyEntry.create({
        data: {
          documentId: document.id,
          actorId: req.user.id,
          action: 'TRANSFER', // Certificate generation
          prevEntryHash: prevHash,
          entryHash,
          caseId: document.caseId,
          notes: `BSA §63 certificate generated by ${req.user.name}`,
        },
      });

      res.status(201).json({ certificate, demo: true });
    } catch (error) {
      next(error);
    }
  }
);

/**
 * GET /api/certificates/:id
 * Get certificate details
 */
const getCertificate = async (req, res, next) => {
  try {
    const certificate = await prisma.certificate.findUnique({
      where: { id: req.params.id },
      include: {
        document: { select: { id: true, filename: true, sha256Hash: true, docType: true } },
        case: { select: { id: true, caseNumber: true, title: true } },
        generator: { select: { id: true, name: true, role: true, serviceBarId: true } },
      },
    });

    if (!certificate) {
      return res.status(404).json({ error: 'Certificate not found' });
    }

    // Check access
    if (req.user.role !== 'SYS' && req.user.department !== certificate.case.department) {
      return res.status(403).json({ error: 'Access denied' });
    }

    res.json({ certificate, demo: true });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/certificates/document/:id
 * List all certificates for a document
 */
router.get('/document/:id', authenticate, requireDocumentAccess, async (req, res, next) => {
  try {
    const certificates = await prisma.certificate.findMany({
      where: { documentId: req.params.id },
      orderBy: { issuedAt: 'desc' },
      include: {
        generator: { select: { name: true, role: true } },
      },
    });

    res.json({ certificates, demo: true });
  } catch (error) {
    next(error);
  }
});

router.get('/:id', authenticate, getCertificate);

/**
 * POST /api/certificates/:id/regenerate
 * Regenerate certificate (creates new version)
 */
router.post(
  '/:id/regenerate',
  authenticate,
  requireRole('IO', 'PP', 'FSL', 'CRT', 'SYS'),
  auditLog('regenerate_certificate', 'DOCUMENT'),
  async (req, res, next) => {
    try {
      const oldCert = await prisma.certificate.findUnique({
        where: { id: req.params.id },
        include: { document: true },
      });

      if (!oldCert) {
        return res.status(404).json({ error: 'Certificate not found' });
      }

      // Generate new certificate
      const certText = generateBSA63Certificate(oldCert.document);
      const hashSummary = sha256(certText);

      const certificate = await prisma.certificate.create({
        data: {
          documentId: oldCert.documentId,
          caseId: oldCert.caseId,
          generatedBy: req.user.id,
          certText,
          hashSummary,
        },
      });

      res.status(201).json({ certificate, demo: true });
    } catch (error) {
      next(error);
    }
  }
);

/**
 * Generate BSA §63 Electronic Evidence Certificate
 * Deterministic template - no LLM involved
 */
function generateBSA63Certificate(document) {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  // Build custody chain summary
  const custodySummary = document.custodyEntries
    .map((entry, i) => {
      const prev = entry.prevEntryHash ? entry.prevEntryHash.slice(0, 16) + '...' : 'GENESIS';
      return `${i + 1}. ${entry.timestamp.toLocaleString('en-IN')} | ${entry.action} | ${entry.actor.name} (${entry.actor.role}) | Prev: ${prev} | Hash: ${entry.entryHash.slice(0, 16)}...`;
    })
    .join('\n');

  // Build signature summary
  const signatureSummary = document.signatures.length > 0
    ? document.signatures
        .map((sig, i) => `${i + 1}. ${sig.signedAt.toLocaleString('en-IN')} | ${sig.user.name} (${sig.user.role}) | Sig: ${sig.signatureValue.slice(0, 24)}...`)
        .join('\n')
    : 'No digital signatures applied yet.';

  return `═══════════════════════════════════════════════════════════════
                    BSA §63 ELECTRONIC EVIDENCE CERTIFICATE
                          (Bharatiya Sakshya Adhiniyam, 2023)
═══════════════════════════════════════════════════════════════

CERTIFICATE NUMBER:     BSA63-${document.case.caseNumber}-${document.id.slice(0, 8).toUpperCase()}
DATE OF ISSUE:          ${dateStr}
TIME OF ISSUE:          ${timeStr} IST

──────────────────────────────────────────────────────────────
1. CASE PARTICULARS
──────────────────────────────────────────────────────────────
Case Number:            ${document.case.caseNumber}
Case Title:             ${document.case.title}
Department:             ${document.case.department}
Investigating Agency:   ${document.department}

──────────────────────────────────────────────────────────────
2. ELECTRONIC RECORD PARTICULARS
──────────────────────────────────────────────────────────────
Document ID:            ${document.id}
File Name:              ${document.filename}
Document Type:          ${document.docType}
Version:                ${document.version}
SHA-256 Hash:           ${document.sha256Hash}
Integrity Status:       ${document.integrity}
Uploaded By:            ${document.uploader.name} (${document.uploader.role})
Service/Bar ID:         ${document.uploader.serviceBarId}
Upload Timestamp:       ${document.uploadedAt.toLocaleString('en-IN')}
Department:             ${document.department}
Restricted:             ${document.restricted ? 'Yes' : 'No'}
Redacted Copy:          ${document.redactedCopy ? 'Yes' : 'No'}
Digitally Signed:       ${document.signed ? 'Yes' : 'No'}
Signed By:              ${document.signedBy || 'N/A'}

──────────────────────────────────────────────────────────────
3. CUSTODY CHAIN (Hash-Linked Ledger)
──────────────────────────────────────────────────────────────
${custodySummary || 'No custody entries recorded.'}

──────────────────────────────────────────────────────────────
4. DIGITAL SIGNATURES
──────────────────────────────────────────────────────────────
${signatureSummary}

──────────────────────────────────────────────────────────────
5. CERTIFICATE VERIFICATION
──────────────────────────────────────────────────────────────
This certificate attests that the electronic record described above
has been maintained in a tamper-evident custody system (ADALAT360)
with cryptographic hash chaining per BSA §63 requirements.

Certificate Hash:       ${hashSummary}
Issuing Officer:        ${req.user.name} (${req.user.role})
Issuing Officer ID:     ${req.user.serviceBarId}
Issuing Department:     ${req.user.department}

═══════════════════════════════════════════════════════════════
This certificate is generated by ADALAT360 (Prototype)
and is valid for evidentiary purposes under BSA §63.
Verification: Recompute SHA-256 of this certificate text and
compare with the Certificate Hash above.
═══════════════════════════════════════════════════════════════`;
}

/**
 * Helper: Get last custody hash for case
 */
async function getLastCustodyHash(caseId) {
  const lastEntry = await prisma.custodyEntry.findFirst({
    where: { caseId },
    orderBy: { timestamp: 'desc' },
    select: { entryHash: true },
  });
  return lastEntry?.entryHash || null;
}

export default router;